# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference

version: '2.1'
orbs:
  unity: game-ci/unity@1.3.0
variables:
  -name: password
  value: Pancakes37&
  -name2: email
  value2: jackrea@ufl.edu
  -name3: key
  value3: SC-XURT-KB6M-MRW5-29CT-4XYE
workflows:
  build:
    jobs:
      - unity/build:
          build-target: StandaloneWindows64
          compress: true
          context: unity
          executor:
            editor_version: 2022.1.20f1
            name: unity/windows-2022
            size: large
            target_platform: windows-il2cpp
          name: build-Windows64-il2cpp
          project-path: 'SWEProject/My project'
          step-name: Build StandaloneWindows64 il2cpp
          unity-license-var-name: key
          unity-password-var-name: password
          unity-username-var-name: email
